[package]
name = "windows-rs-learn"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = { version = "0.61", features = ["Win32_System_Memory", "Win32_Foundation", "Win32_System_SystemServices", "Win32_UI_WindowsAndMessaging"] }
windows-core = "0.61"
