[package]
name = "windows-rs-learn"
version = "0.1.0"
edition.workspace = true

[dependencies]
windows = { workspace = true, features = ["Win32_System_Memory", "Win32_Foundation", "Win32_System_SystemServices", "Win32_UI_WindowsAndMessaging"] }
windows-core.workspace = true
